In [2]:
import numpy as np

In [ ]:
#dot product
x = np.array([-2,3])
y = np.array([3,-4])
print(np.dot(x,y))

-18


In [ ]:
#cosine similarity
def cosine_similarity(a,b):
  norm_a = np.linalg.norm(a)
  norm_b = np.linalg.norm(b)
  dot_product = np.dot(a,b)
  cosine_simlarity = dot_product/(norm_a*norm_b)
  return cosine_simlarity

In [ ]:
a = np.array([2,3])
b = np.array([3,4])

print(cosine_similarity(a,b))

0.9984603532054125


In [ ]:
#matrix similarity
X = np.array([[1,2,3],
             [4,5,6],
             [1,0,0]
             ])
dot_products = X @ X.T

norms = np.linalg.norm(X,axis = 1)
norm_matrix = np.outer(norms,norms)
cosine_sim = dot_products/norm_matrix
print(cosine_sim)

[[1.         0.97463185 0.26726124]
 [0.97463185 1.         0.45584231]
 [0.26726124 0.45584231 1.        ]]


In [ ]:
#matrix multiplication
x  = np.array([
    [3,4,5],
    [1,2,3],
    [4,6,7]
])

y  = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
#option A
result = x@y
print(result)

#option B
result = np.matmul(x,y)
print(result)

#option C
result = np.dot(x,y)
print(result)


[[ 54  66  78]
 [ 30  36  42]
 [ 77  94 111]]
[[ 54  66  78]
 [ 30  36  42]
 [ 77  94 111]]
[[ 54  66  78]
 [ 30  36  42]
 [ 77  94 111]]


In [ ]:
#benchmark testing for nested loops
import numpy as np
import time

x = np.random.rand(500,100)

#defining 
def cosineloop(x):
    n = x.shape[0]
    similarity = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            dot = np.dot(x[i],x[j])
            norm_i = np.linalg.norm(x[i])
            norm_j = np.linalg.norm(x[j])
            similarity[i][j] = dot / (norm_i * norm_j)
    return similarity

#timing it
start = time.time()u
cosineloop(x)
print("Loop time: ", time.time()-start)

Loop time:  0.9050483703613281


In [ ]:
#benchmark testing for vectorized version
import numpy as np
import time

x = np.random.rand(500,100)

#defining
def cosine_vectorized(x):
    dot_products = x @ x.T
    norms = np.linalg.norm(x, axis=1)
    norm_matrix = np.outer(norms, norms)
    return dot_products / norm_matrix

#timing it
start = time.time()
cosine_vectorized(x)
print("Vectorized time:", time.time() - start)

Vectorized time: 0.012018680572509766


Vectorised version is MUCH faster